### ISSUE TITLE
Button states are swapped

### ISSUE THREAD

**Issue by BryceBeagle** [sunhacksio/sunhacks-98#6]
![image](https://user-images.githubusercontent.com/5437880/124963405-9de4a400-dfd4-11eb-8af2-ab1500a0b81d.png)

Depressed w/o mousedown
Raised w/ mousedown

**Comment by PaHorton** [comment]
Dark Mode error

**Comment by BryceBeagle** [comment]
Feature request: compatibility with Dark Reader 😏
